name: CI/CD-2

on:
  push:
    branches: 
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@vS
    - name: Display Message
      run: echo "Building Application"
    - name: Run tests
      run: echo "testing successfu"
    - name: Deploy
      run: echo "deployment successful"